name: Regenerate source code

on:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: latest
      - run: npm ci
      - run: npm run codegen
      - uses: peter-evans/create-pull-request@v5
