name: Generate API types

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

permissions:
  contents: write
  pull-requests: write

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
      - run: deno task codegen
      - uses: actions/create-github-app-token@v1
        id: create-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.create-token.outputs.token }}
          branch: "update-api-types"
          commit-message: "chore: generate latest Bot API types"
          # TODO: Automatically insert Bot API version
          title: "feat: update Bot API types"
